server.port=${PORT:8080}
spring.application.name=gestao-estoque

# aqui banco de dados
spring.datasource.url=jdbc:postgresql://postgres:yGpvcpUqYOosETXiMLGCFfXHnLjOyEuK@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=yGpvcpUqYOosETXiMLGCFfXHnLjOyEuK
spring.datasource.driver-class-name=org.postgresql.Driver

# aqui Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true