spring.application.name=gestao-estoque
spring.datasource.url=jdbc:postgresql://postgres:yGpvcpUqYOosETXiMLGCFfXHnLjOyEuK@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=yGpvcpUqYOosETXiMLGCFfXHnLjOyEuK
spring.jpa.hibernate.ddl-auto=update
spring.jpa,properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect